name: Continuous integration

on: push

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
    - name: Style checking
      run: |
        flake8 reals tests --max-line-length 120
    - name: Type checking
      run: |
        mypy reals tests
    - name: Unit tests
      run: |
        pytest tests --timeout=2
